"use strict";

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert(
      "Memes",
      [
        {
          userId: 1,
          headline: "hello world",
          caption: "test caption",
          link: "https://i.ibb.co/fk8BdPM/EMTXo1p-Ww-AEUR0g.jpg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 2,
          headline: "hello world",
          caption: "test caption",
          link: "https://i.ibb.co/LvQ8g34/0-SHcvkzua-TQRg-Bg-Cq.png",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 3,
          headline: "hello world",
          caption: "test caption",
          link: "https://i.ibb.co/2tPvcRh/1604584610295.jpg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 4,
          headline: "hello world",
          caption: "test caption",
          link: "https://i.ibb.co/3kHZnst/You-wont-get-a-job-by-staying-on-your-computer-all-day-371.jpg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 5,
          headline: "hello world",
          caption: "test caption",
          link: "https://i.ibb.co/5jF2gs8/1627109107-714-Daily-Dose-of-Programming-Jokes-Best-programming-meme-compilations.jpg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 1,
          headline: "hello world",
          caption: "test caption",
          link: "https://i.ibb.co/tZsfnkG/programming-or-googling.jpg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 2,
          headline: "hello world",
          caption: "test caption",
          link: "https://i.ibb.co/HXy3LFy/EPmn-Mw3-Xs-AE1i1-C.jpg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 3,
          headline: "hello world",
          caption: "test caption",
          link: "https://i.ibb.co/6mMZrLv/26073214-140345453318183-7449441902409023488-n.jpg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 4,
          headline: "hello world",
          caption: "test caption",
          link: "https://i.ibb.co/QmqBwmk/states-of-a-programmer.png",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 5,
          headline: "hello world",
          caption: "test caption",
          link: "https://i.ibb.co/gygRK1Y/86588810.jpg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 1,
          headline: "hello world",
          caption: "test caption",
          link: "https://i.ibb.co/gMK7v6v/images.jpg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 2,
          headline: "hello world",
          caption: "test caption",
          link: "https://i.ibb.co/DQh5zdC/5f7c55ff75e76.jpg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 3,
          headline: "hello world",
          caption: "test caption",
          link: "https://i.ibb.co/1TmsjHj/maxresdefault.jpg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 4,
          headline: "hello world",
          caption: "test caption",
          link: "https://i.ibb.co/fvgBHwL/0-r6i-Qzljiu-Jav-Vx-RM.jpg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 5,
          headline: "hello world",
          caption: "test caption",
          link: "https://i.ibb.co/d6htf48/0-MU2vn-VDQMHG13p-Pw.png",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 1,
          headline: "hello world",
          caption: "test caption",
          link: "https://i.ibb.co/q08Jh6Q/asked-draw-flowchart-my-code-tdev-meme-y-start-magic-end.jpg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 2,
          headline: "hello world",
          caption: "test caption",
          link: "https://i.ibb.co/tC0kxZP/60d33bf3a2121cc74f72a286-0-AEnn-ZYBAYzm-SXzy-Gaopjv-EGKKO1y-Fqf-z-MXq-FTAT6v-UDf-XVPRif-I3-J8o-Bj-ZU.png",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 3,
          headline: "hello world",
          caption: "test caption",
          link: "https://i.ibb.co/1JYRtdk/semicolon2.jpg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 4,
          headline: "hello world",
          caption: "test caption",
          link: "https://i.ibb.co/dW1v1zS/Untitled-63-1.png",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 5,
          headline: "hello world",
          caption: "test caption",
          link: "https://i.ibb.co/SXTPYBc/0-8-WOQq-XZd-Bw-C3-BC43.jpg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("Memes", null, {});
  },
};
